name: Auto Merge Claude Approved PRs

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
