name: Claude Auto Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run Claude Code Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ steps.app-token.outputs.token }}
          model: claude-3.5-sonnet
          enable_code_review: true
          review_comment_mode: full      # 详细评论模式
          max_review_comments: 20        # 最多20条评论
          require_approval: true         # 审核通过才合并
